language: node_js
node_js:
- '0.11'
- '0.10'
deploy:
  provider: npm
  email: gvg.fede@gmail.com
  api_key:
    secure: BzT8uo/EMU7XW/5jl7EeITW6OGEScQ+tk1ndubdpScf1vnHoYsuyYBGsEkPJ16HXBcjVcCmE3bmGcBejRgviwQToJaYU3MRCWIo8jYkaDDieIoTMavdhKdyPTz7yIBT+FNx72SxBlEBb4y1WT/rC+mNFQJG4rCPqKdg9thzMIFg=
  on:
    tags: true
    repo: Meesayen/es6-gulp-boilerplate
    all_branches: true
